# ====================================================
#   Copyright (C)2019 All rights reserved.
#
#   Author        : Pandora
#   Email         : pandora@github.com
#   File Name     : makefile
#   Last Modified : 2019-03-08 10:34
#   Describe      :
#
# ====================================================

seq_printf: file.o
	gcc file.o seq_printf.c -o seq_printf

file.o:
	gcc -c file.c

clear:
	rm -v *.o
